server:
  port: 9999
spring:
  datasource:
    username: root
    password: Wcxwan582453
    url: jdbc:mysql://localhost:3306/x_user
    driver-class-name: com.mysql.cj.jdbc.Driver
redis:
  port: 6379
  host: localhost

logging:
  level:
    com.lantu: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1